### ISSUE TITLE
提交试用报错

### ISSUE THREAD

**Issue by Peter-90** [zhx47/jd_scripts#1]
<img width="1004" alt="image" src="https://github.com/zhx47/jd_scripts/assets/22003137/8c48f956-4bf4-4d32-8bad-4f4257578380">
<img width="392" alt="image" src="https://github.com/zhx47/jd_scripts/assets/22003137/09a0176d-eb59-4f7c-bd9d-57c075ce11f9">
在使用的代理的情况下，提交申请还是失败，基本跑不了，大佬能修修吗

**Comment by zhx47** [comment]
过几天会修，现在好像强制校验log了，这几天放假没弄，代理后续不需要了，已经找到原因了

**Comment by Sirius2s** [comment]
> 过几天会修，现在好像强制校验log了，这几天放假没弄，代理后续不需要了，已经找到原因了

获取列表只能到10页，第11开始就403了。试过 延长发请求的间隔时间，改代理端口，都没解决到。请问我这可能是啥情况呢？

**Comment by zhx47** [comment]
> > 过几天会修，现在好像强制校验log了，这几天放假没弄，代理后续不需要了，已经找到原因了
> 
> 获取列表只能到10页，第11开始就403了。试过 延长发请求的间隔时间，改代理端口，都没解决到。请问我这可能是啥情况呢？

这个还不太清楚，回头可以仔细看下，但是获取列表接口这次更新使用的是h5st4.4 lite，一个纯本地算法，处理后应该没什么问题。

**Comment by Peter-90** [comment]
> 过几天会修，现在好像强制校验log了，这几天放假没弄，代理后续不需要了，已经找到原因了

好的 大佬辛苦了 感谢大佬

**Comment by zhx47** [comment]
> > > 获取列表只能到10页，第11开始就403了。试过 延长发请求的间隔时间，改代理端口，都没解决到。请问我这可能是啥情况呢？
> > 
> > 你可以试下，如果脚本跑出403，同网络下看看这个账号在浏览器环境或者APP能否正常继续加载，如果能加载说明脚本算法有些东西不太对。要是浏览器或者APP也不行，应该是被限流了
> 
> 已验证：脚本403的时候，APP同网/账号，能正常加载列表。
> 403的时候，先结束脚本进程：马上重新运行还是403，隔一两分钟或多几分钟再运行又可以加载。
> 不知道是不是脚本生成的哪个CK参数失效了，大佬再看看？

比较奇怪，不过我log快弄好了，这两天测一测估计就能勉强跑了，这个后面再看看

**Comment by zhx47** [comment]
已更新，订阅链接变了
