### ISSUE TITLE
出现错误“客户端版本不满足条件”

### ISSUE THREAD

**Issue by midpoint** [zhx47/jd_scripts#11]
## 开始执行... 2024-09-04 09:30:10

🔔京东试用, 开始!

遇到问题请先看脚本内注释；解决不了可联系https://t.me/zhouya47

====================共3个京东账号Cookie=================

============脚本执行时间：2024/09/04 09:30:11=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>>>

共3个京东账号

开始【京东账号1】m******

今日剩余试用机会5
getInterfaceData -> {"funcName":"blog","real_msg":"客户端版本不满足条件"}
getInterfaceData -> {"funcName":"init"}

**Comment by zhx47** [comment]
无价值反馈，关闭issue
