### ISSUE TITLE
不能用了老哥，

### ISSUE THREAD

**Issue by wodeweiyimpm** [zhx47/jd_scripts#12]
今日剩余试用机会5
getInterfaceData -> {"funcName":"blog","real_msg":"客户端版本不满足条件"}
getInterfaceData -> {"funcName":"init"}
403，第 1 次重试
间隔等待中，请等待5秒 

403，第 2 次重试
间隔等待中，请等待5秒 

403，第 3 次重试
间隔等待中，请等待5秒 

稍后将执行试用申请，请等待 5 秒

试用申请执行完毕...
京东试用 👤 京东账号1
⚠️ 本次执行没有申请试用商品
🎉 0个商品待领取
🎉 0个商品已领取
🎉 0个商品已完成
🗑 0个商品已放弃

**Comment by zhx47** [comment]
等有时间再研究吧，大概知道是什么问题

**Comment by wodeweiyimpm** [comment]
修复了么，老哥

**Comment by ldcr1319** [comment]
等修复

**Comment by wodeweiyimpm** [comment]
别人修复了&nbsp; 可以用&nbsp; 丢这里面 utils


___夏、末。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhx47/jd_scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月17日(星期四) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhx47/jd_scripts] 不能用了老哥， (Issue #12)





 
等修复

**Comment by uminoai** [comment]
> 别人修复了&nbsp; 可以用&nbsp; 丢这里面 utils
> […](#)
> ___夏、末。 ***@***.*** &nbsp;
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhx47/jd_scripts" ***@***.***&gt;; 发送时间:&nbsp;2024年10月17日(星期四) 下午3:09 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhx47/jd_scripts] 不能用了老哥， (Issue #12) 等修复 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没看到文件啊

**Comment by zhx47** [comment]
试一下，已经加了jsToken，不过你已经搞定了，我就关闭issue了
