### ISSUE TITLE
用不了，提示：客户端版本不满足条件

### ISSUE THREAD

**Issue by midpoint** [zhx47/jd_scripts#15]
![jd-try](https://github.com/user-attachments/assets/bc92e7b2-0389-4051-aa5f-3f1938ed7359)

**Comment by zhx47** [comment]
这个日志是正常的，调试日志我没取消，使用的pc ua，这个log算法里面blog部分我懒得弄了，所以提示客户端版本不满足条件，这个本来就是pc环境正常的日志信息。

**Comment by midpoint** [comment]
只有这个信息，后面没有其他信息了

**Comment by zhx47** [comment]
反正目前贴图内均为正常内容
