### ISSUE TITLE
大佬，提示jsToken.js丢失，并且版本低了。

### ISSUE THREAD

**Issue by xixilove8** [zhx47/jd_scripts#16]
大佬，提示jsToken.js丢失，并且版本低了。

**Comment by zhx47** [comment]
忘记上传了，我擦...

**Comment by xixilove8** [comment]
辛苦啦，邮件已收到，我会尽快回复。

**Comment by xixilove8** [comment]
大佬给力，等你更新

**Comment by zhx47** [comment]
上传了，你更新下试试，不一定能用，而且公开库里面应该也有，这个本来是我用来测试h5st的，但是现在试用里面其他的检测七七八八的弄我有点烦

**Comment by xixilove8** [comment]
重新更新已经可以用啦，谢谢大佬~
