### ISSUE TITLE
找不到QL 

### ISSUE THREAD

**Issue by mk2leo** [zhx47/jd_scripts#4]
![image](https://github.com/zhx47/jd_scripts/assets/72913711/b108c792-b294-4706-b4e4-abf30988852e)

查看了容器路徑是沒有錯的.也完整拉下了倉庫文件.

**Comment by zhx47** [comment]
使用新版本ql，然后使用订阅功能复制readme中的命令

**Comment by zhx47** [comment]
目前公开库已经包含该脚本，只是跑试用可以直接从公开库拉取
