### ISSUE TITLE
可以分享下base64的uncode/decode吗？

### ISSUE THREAD

**Issue by devcxm** [zhx47/jd_scripts#7]
想解密接口请求参数~

**Comment by zhx47** [comment]
你说的是4.7的env吧，4.7之前的就是标准的算法，4.7 tg有发过uncode，可以自己翻一下频道，关于decode可以反过来处理

**Comment by zhx47** [comment]
> > 你说的是4.7的env吧，4.7之前的就是标准的算法，4.7 tg有发过uncode，可以自己翻一下频道，关于decode可以反过来处理
> 
> @zhx47 
> 把encode的代码抄下来跑起来了，但是目前没想到decode思路，无符号右移和按位与操作是不可逆向计算，无从下手。。。大佬指导下
> 
> PS：TG的uncode代码折叠起来看不到
> <img width="323" alt="Screenshot 2024-06-22 at 00 32 32" src="https://github.com/zhx47/jd_scripts/assets/8568955/53565907-f5f9-4dcc-b27e-51e479742c09">
> 

tg不是把一二三步给分清楚了吗，然后你只需要反过来执行三二一步每一步的反向操作就好了，京东自己添加的utils的两个方法本来就是对应关系，第二步我也说了是自定义字典的base64.stringfy，他的对应不就是parse嘛。

光把代码搬走了没用的，得看一下，就那么小几十行
