### ISSUE TITLE
老哥这是哪里的问题

### ISSUE THREAD

**Issue by WANGLISHAO** [zhx47/jd_scripts#8]
![mmexport1721095330796.png](https://github.com/user-attachments/assets/8ec0a7f4-4477-4f0a-afc5-64f9d0dc945b)

**Comment by zhx47** [comment]
h5st获取我改成接口了，不过是cloudflare代理的，你可以自行搭建一个，将地址进行替换
https://hub.docker.com/r/zhx47/jd_h5st_server
