### ISSUE TITLE
客户端版本不满足条件

### ISSUE THREAD

**Issue by a131656** [zhx47/jd_scripts#9]
今日剩余试用机会5
getInterfaceData -> {"funcName":"blog","real_msg":"客户端版本不满足条件"}
getInterfaceData -> {"funcName":"init"}
❗️ 京东试用 运行错误！
Error: socket hang up

**Comment by 5jwoj** [comment]
同样的报错，tg的联系方式也失效 了

**Comment by zhx47** [comment]
正常debug信息，忽略，现在可以自建h5st算法了，之前内置的一些半成品去除了，因为腾讯云老是有人攻击，所以我上一段时间停了
